### ISSUE TITLE
Serilog 4

### ISSUE THREAD

**Issue by spointeau** [serilog/serilog-sinks-observable#10]
Is it possible to update the nuget with the dependency on serilog 4 ?

**Comment by bartelink** [comment]
@nblumhardt is in the middle of doing it across all repos - atm it's coincidentally last on the list in https://github.com/serilog/serilog/issues/2075 - but the takeaway should be more that it's a big list, than that this is the single lowest priority sink!

If you need it expedited, you could examine a batch of those in adjacent repos and create a PR to do the equivalent.

**Comment by Numpsy** [comment]
I've made some changes in #11 if anyone fancies a look (I don't actually use this sink myself, and there is only a single unit test)

**Comment by spointeau** [comment]
this is really great thank you!
Do you have a nuget published ? if so I can deploy my app in test with this beta nuget to give you a quick feedback

**Comment by Numpsy** [comment]
There are nuget packages attached to the CI build results at https://ci.appveyor.com/project/serilog/serilog-sinks-observable/builds/50099184/artifacts

**Comment by spointeau** [comment]
OK, I do it and keep you informed

**Comment by spointeau** [comment]
I just did the preliminary testing, all good, I will now let the application in TEST for a few hours and let you know.

**Comment by spointeau** [comment]
It seems all OK for us. Thank you again

**Comment by Numpsy** [comment]
@spointeau The new 3.0.0 release published to nuget.org should be all up to date with Serilog 4 now.
