### ISSUE TITLE
MessageTemplate for observable sink?

### ISSUE THREAD

**Issue by cknaap** [serilog/serilog-sinks-observable#6]
Since you can't set the MessageTemplate easily on a LogEvent, it would be nice to be able to specify it in the WriteTo.Observable method, like we can on WriteTo.Console.
That way you can control what the observer gets by default if it calls logEvent.RenderMessage().

**Comment by nblumhardt** [comment]
Thanks for the suggestion :+1: 

Instead of calling `RenderMessage()`, you can create a `Serilog.Formatting.Display.MessageTemplateTextFormatter` and use that to render the event within the observer - this is (essentially) what the file/console sinks do. Let me know if you need more info!

**Comment by rschoenbach** [comment]
@nblumhardt If possible, I could use some more information.

`RenderMessage()` appears to work fine for my use case but I want to make sure I am properly following the recommendations.

**Comment by nblumhardt** [comment]
Hi @rschoenbach - `RenderMessage()` will only include the log message in the output, not (for example) the timestamp or level. `MessageTemplateTextFormatter` enables more formatting options like these, and also adds the ability to render embedded structured data using JSON-style formatting, etc.

In short, if `RenderMessage()` covers your needs that's fine :+1:
