### ISSUE TITLE
Adding Serilog.Sinks.Observable to App Config

### ISSUE THREAD

**Issue by noahsyed** [serilog/serilog-sinks-observable#8]
What's the syntax to add Serilog.Sinks.Observable in App Settings, I was able to add the ColoredConsole and the RollingFile sinks but Observable sink is a bit tricky, can you share the share syntax for that?

        <add key="serilog:using:ColoredConsole" value="Serilog.Sinks.ColoredConsole" />
        <add key="serilog:write-to:ColoredConsole.level" value="Debug" />
        <add key="serilog:write-to:ColoredConsole.outputTemplate" value="...." />

        <add key="serilog:using:RollingFile" value="Serilog.Sinks.RollingFile" />
        <add key="serilog:write-to:RollingFile.pathFormat" value="C:\Logs\myapp-{Date}.txt" />

Thanks,
Noah.

**Comment by noahsyed** [comment]
@nblumhardt - Nick, any suggestions will be super useful!

**Comment by nblumhardt** [comment]
Observable can still be added in code, along with the other sinks from app settings - there's no way to configure observables from app settings at this point. HTH!

**Comment by noahsyed** [comment]
Thanks!
